# Generated by Django 5.0.2 on 2024-02-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=50)),
                ('S_Email', models.EmailField(max_length=20)),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=50)),
                ('L_name', models.CharField(max_length=50)),
                ('User_name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
